name: facam backend Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'facam-backend/**'
  # workflow_dispatch: # production
  #   inputs:
  #     logLevel:
  #       description: 'Log level'
  #       required: true
  #       default: 'warning'
  #     tags:
  #       description: 'Test scenario tags'

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: facam-backend
  ECS_NAMESPACE: ecs-cluster

jobs:
  mvn-build:
    name: mvn-build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file ./facam-backend/pom.xml

  ecr-build-push:
    name: ecr-build-push
    runs-on: ubuntu-latest
    needs: mvn-build
    environment: development

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: ${{ env.AWS_ECR_PULL_PUSH }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPOSITORY }}
          #IMAGE_TAG: ${{ github.sha }}
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
          docker build -t $REGISTRY/$REPOSITORY:$VERSION .
          docker push $REGISTRY/$REPOSITORY:$VERSION
  
  # ecs-deploy:
  #   name: ecs-deploy
  #   runs-on: ubuntu-latest
  #   needs: ecr-build-push
  #   environment: development

  #   steps:
  #     - name: Configure AWS credentials
  #       uses: 